name: CI/CD Pipeline Triggered by AWS Lambda

on:
  workflow_dispatch: # Allows the workflow to be triggered manually or via API

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: |
          echo "Running tests..."
          if [ -f "test.py" ]; then python3 test.py; else echo "test.py not found, skipping..."; fi

  deploy:
    name: Deploy Application
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Deploy to Server
        run: |
          echo "Deploying application..."
          if [ -f "test.py" ]; then python3 test.py; else echo "test.py not found, skipping..."; fi
