name: CI/CD Pipeline

on:
  workflow_dispatch:  # Required for manual triggers via API

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print a message
        run: echo "Workflow triggered successfully!"
